### ISSUE TITLE
ADOL-C build directory

### ISSUE THREAD

**Issue by chrisjordansquire** [b45ch1/pyadolc#18]
The readme is unclear where ADOL-C should be in the build directory. If ADOL-C is checked out into ~/workspace/adol-c/ADOL-C then the scons build script throws errors because it looks for includes in -I${HOME}/workspace/adol-c/ADOL-C/include instead of -I{HOME}/workspace/adol-c/ADOL-C/ADOL-C/include. To get pyadolc to build I first built ADOL-C as specified in ~/workspace/adol-c/ADOL-C-TRUNK and then copied the ADOL-C subdirectory, which contained the built files, into ~/workspace/adol-c/ADOL-C. With that change scons built successfully.

**Comment by b45ch1** [comment]
The canonical README.rst, bootstrap.sh and setup.py provide information on how to setup ADOL-C .
