### ISSUE TITLE
wrapper functions drop return code

### ISSUE THREAD

**Issue by utke1** [b45ch1/pyadolc#20]
Having the return code passed back from things like gradient/jacobian/hessian seems to be the only way to detect situations like invalid tape but in the current implementation e.g. for hessian in wrapped_functions.py the return code is dropped.

**Comment by b45ch1** [comment]
The original C++ API is available in adolc._adolc where you can also access the return values.

**Example**:

```
import adolc
help(adolc._adolc.jacobian)

Help on built-in function jacobian in module adolc._adolc:

jacobian(...)
    jacobian( (int)arg1, (int)arg2, (int)arg3, (object)arg4, (object)arg5) -> int :
    
        C++ signature :
            int jacobian(short,int,int,boost::python::numeric::array {lvalue},boost::python::numeric::array {lvalue})
```

**Comment by utke1** [comment]
So, are you suggesting that the interfaces in wrapped_functions.py are deprecated now? If yes, that would be rather sad because I liked the cleaned up argument list. It is hard to justify particularly in python the need to specify n and m in the argument list given that they are encoded in the trace anyway. If not, then one still doesn't have a clue that the returned results may be all bogus. 
So in short, if I may,  I think this is not a sufficient rationale to close the issue.  :-)

**Comment by b45ch1** [comment]
No, I didn't want to suggest that the interfaces in wrapped_functions.py are deprecated. But in case you want access to the lower level C++ functions, there is nothing stopping you.
But maybe I'm misunderstanding you ;) What are you suggesting?

**Comment by utke1** [comment]
So, now that I actually need it for my use case ... what I am suggesting is e.g. an small exception class that contains the error return code, so for example in my case a -1 returned by gradient for a tape evaluated at an invalid point.  Without the exception this there is no prgrammatic indication that "gradient" actually failed. So,  if you don't mind and reopen the issue I would just add the code and provide it as a pull request for you.
