### ISSUE TITLE
Do not use ==/!= None

### ISSUE THREAD

**Issue by seberg** [b45ch1/pyadolc#23]
Adolc still uses `== None` and `!= None` in some places. These should be replaced with `is None` and `is not None`. This is better style, but mostly NumPy nowadays warns about not using `== None` because we want to make this an elementwise comparison. So if you have `if arr == None: ...` it will start failing at some point.
(There are deprecation warnings for this in place, but since they are not often seen, and I noticed this, thought I would mention, if I ever run into the warning again I might create a PR, but I don't use pyadolc a lot at the moment).

**Comment by b45ch1** [comment]
Thanks for the hint. Fixed in 129f3e9856b0934b5b773a0c3bea355874c69ec1

**Comment by seberg** [comment]
Great, thanks!
